In [16]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from scipy.signal import butter, filtfilt, iirnotch, find_peaks
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import SGD, Adam
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping

In [2]:
def preprocess_emg_signal(file_path, fs = 1000, mvc_dict=None):
    df = pd.read_csv(file_path)
    df_processed = df.copy()
    channels = [f'channel{i}' for i in range(1, 9)]
    nyq = 0.5 * fs
    b_band, a_band = butter(4, [20/nyq, 450/nyq], btype='band')
    b_low, a_low = butter(4, 10/nyq, btype='low')

    for ch in channels:
        if ch not in df.columns:
            print(f"Warning: cannot find {ch} in the file!")
            continue
        raw_sig = df[ch].fillna(0).values
        filtered = filtfilt(b_band, a_band, raw_sig)
        rectified = np.abs(filtered)
        envelope = filtfilt(b_low, a_low, rectified)
        envelope = np.maximum(envelope, 0)
        df_processed[ch] = envelope 
    for ch in channels:
        df_processed[ch] = df_processed.groupby('label')[ch].transform(
            lambda x: (x / (x.max() if x.max() > 0 else 1)) * 100
        )

        print(df_processed)

    output_file = file_path.replace('.csv', '_processed.csv')
    df_processed.to_csv(output_file, index=False)

    print("Finishing Preprocessing dataset")

    return df_processed

In [3]:
file_path = r"datasets\train\EMG-data.csv"
df = preprocess_emg_signal(file_path)
df

          time  channel1  channel2      channel3  channel4  channel5  \
0            1  0.505663  0.000003  0.000000e+00  0.000004  0.000000
1            5  0.540232  0.000003  4.408627e-07  0.000005  0.000000
2            6  0.574307  0.000004  1.715085e-06  0.000006  0.000000
3            7  0.607811  0.000005  2.980392e-06  0.000007  0.000000
4            8  0.640667  0.000005  4.234796e-06  0.000008  0.000000
...        ...       ...       ...           ...       ...       ...
4237902  50962  1.788038  0.000005  7.649281e-06  0.000008  0.000035
4237903  50963  1.784848  0.000005  7.643663e-06  0.000008  0.000035
4237904  50964  1.782188  0.000005  7.638959e-06  0.000008  0.000035
4237905  50965  1.780000  0.000005  7.635074e-06  0.000008  0.000035
4237906  50966  1.778226  0.000005  7.631911e-06  0.000008  0.000035

             channel6      channel7      channel8  class  label
0        4.586132e-07  1.549889e-07  0.000000e+00      0      1
1        9.650049e-07  2.889740e-07  0.000000e+00      0      1
2        1.462514e-06  4.258308e-07  0.000000e+00      0      1
3        1.950233e-06  5.653865e-07  0.000000e+00      0      1
4        2.427283e-06  7.074600e-07  4.486659e-08      0      1
...               ...           ...           ...    ...    ...
4237902  2.574302e-05  1.416464e-05  2.218771e-05      0     36
4237903  2.573004e-05  1.418005e-05  2.218419e-05      0     36
4237904  2.571932e-05  1.419285e-05  2.218109e-05      0     36
4237905  2.571058e-05  1.420334e-05  2.217842e-05      0     36
4237906  2.570355e-05  1.421181e-05  2.217615e-05      0     36

[4237907 rows x 11 columns]
          time  channel1  channel2      channel3  channel4  channel5  \
0            1  0.505663  0.426684  0.000000e+00  0.000004  0.000000
1            5  0.540232  0.521757  4.408627e-07  0.000005  0.000000
2            6  0.574307  0.618733  1.715085e-06  0.000006  0.000000
3            7  0.607811  0.717485  2.980392e-06  0.000007  0.000000
4            8  0.640667  0.817878  4.234796e-06  0.000008  0.000000
...        ...       ...       ...           ...       ...       ...
4237902  50962  1.788038  1.957604  7.649281e-06  0.000008  0.000035
4237903  50963  1.784848  1.957495  7.643663e-06  0.000008  0.000035
4237904  50964  1.782188  1.957413  7.638959e-06  0.000008  0.000035
4237905  50965  1.780000  1.957352  7.635074e-06  0.000008  0.000035
4237906  50966  1.778226  1.957306  7.631911e-06  0.000008  0.000035

             channel6      channel7      channel8  class  label
0        4.586132e-07  1.549889e-07  0.000000e+00      0      1
1        9.650049e-07  2.889740e-07  0.000000e+00      0      1
2        1.462514e-06  4.258308e-07  0.000000e+00      0      1
3        1.950233e-06  5.653865e-07  0.000000e+00      0      1
4        2.427283e-06  7.074600e-07  4.486659e-08      0      1
...               ...           ...           ...    ...    ...
4237902  2.574302e-05  1.416464e-05  2.218771e-05      0     36
4237903  2.573004e-05  1.418005e-05  2.218419e-05      0     36
4237904  2.571932e-05  1.419285e-05  2.218109e-05      0     36
4237905  2.571058e-05  1.420334e-05  2.217842e-05      0     36
4237906  2.570355e-05  1.421181e-05  2.217615e-05      0     36

[4237907 rows x 11 columns]
          time  channel1  channel2  channel3  channel4  channel5  \
0            1  0.505663  0.426684  0.000000  0.000004  0.000000
1            5  0.540232  0.521757  0.077848  0.000005  0.000000
2            6  0.574307  0.618733  0.302852  0.000006  0.000000
3            7  0.607811  0.717485  0.526282  0.000007  0.000000
4            8  0.640667  0.817878  0.747786  0.000008  0.000000
...        ...       ...       ...       ...       ...       ...
4237902  50962  1.788038  1.957604  4.085815  0.000008  0.000035
4237903  50963  1.784848  1.957495  4.082814  0.000008  0.000035
4237904  50964  1.782188  1.957413  4.080302  0.000008  0.000035
4237905  50965  1.780000  1.957352  4.078227  0.000008  0.000035
4237906  50966  1.778226  1.957306  4.076537  0.000008  0.000035

             channel6      channel7      channel8  class  label
0        4.586132e-07  1.549889e-07  0.000000e+00      0      1
1        9.650049e-07  2.889740e-07  0.000000e+00      0      1
2        1.462514e-06  4.258308e-07  0.000000e+00      0      1
3        1.950233e-06  5.653865e-07  0.000000e+00      0      1
4        2.427283e-06  7.074600e-07  4.486659e-08      0      1
...               ...           ...           ...    ...    ...
4237902  2.574302e-05  1.416464e-05  2.218771e-05      0     36
4237903  2.573004e-05  1.418005e-05  2.218419e-05      0     36
4237904  2.571932e-05  1.419285e-05  2.218109e-05      0     36
4237905  2.571058e-05  1.420334e-05  2.217842e-05      0     36
4237906  2.570355e-05  1.421181e-05  2.217615e-05      0     36

[4237907 rows x 11 columns]
          time  channel1  channel2  channel3  channel4  channel5  \
0            1  0.505663  0.426684  0.000000  0.569724  0.000000
1            5  0.540232  0.521757  0.077848  0.747488  0.000000
2            6  0.574307  0.618733  0.302852  0.923943  0.000000
3            7  0.607811  0.717485  0.526282  1.098786  0.000000
4            8  0.640667  0.817878  0.747786  1.271718  0.000000
...        ...       ...       ...       ...       ...       ...
4237902  50962  1.788038  1.957604  4.085815  1.574949  0.000035
4237903  50963  1.784848  1.957495  4.082814  1.576233  0.000035
4237904  50964  1.782188  1.957413  4.080302  1.577300  0.000035
4237905  50965  1.780000  1.957352  4.078227  1.578175  0.000035
4237906  50966  1.778226  1.957306  4.076537  1.578882  0.000035

             channel6      channel7      channel8  class  label
0        4.586132e-07  1.549889e-07  0.000000e+00      0      1
1        9.650049e-07  2.889740e-07  0.000000e+00      0      1
2        1.462514e-06  4.258308e-07  0.000000e+00      0      1
3        1.950233e-06  5.653865e-07  0.000000e+00      0      1
4        2.427283e-06  7.074600e-07  4.486659e-08      0      1
...               ...           ...           ...    ...    ...
4237902  2.574302e-05  1.416464e-05  2.218771e-05      0     36
4237903  2.573004e-05  1.418005e-05  2.218419e-05      0     36
4237904  2.571932e-05  1.419285e-05  2.218109e-05      0     36
4237905  2.571058e-05  1.420334e-05  2.217842e-05      0     36
4237906  2.570355e-05  1.421181e-05  2.217615e-05      0     36

[4237907 rows x 11 columns]
          time  channel1  channel2  channel3  channel4  channel5  \
0            1  0.505663  0.426684  0.000000  0.569724  0.000000
1            5  0.540232  0.521757  0.077848  0.747488  0.000000
2            6  0.574307  0.618733  0.302852  0.923943  0.000000
3            7  0.607811  0.717485  0.526282  1.098786  0.000000
4            8  0.640667  0.817878  0.747786  1.271718  0.000000
...        ...       ...       ...       ...       ...       ...
4237902  50962  1.788038  1.957604  4.085815  1.574949  5.676281
4237903  50963  1.784848  1.957495  4.082814  1.576233  5.682195
4237904  50964  1.782188  1.957413  4.080302  1.577300  5.687095
4237905  50965  1.780000  1.957352  4.078227  1.578175  5.691099
4237906  50966  1.778226  1.957306  4.076537  1.578882  5.694322

             channel6      channel7      channel8  class  label
0        4.586132e-07  1.549889e-07  0.000000e+00      0      1
1        9.650049e-07  2.889740e-07  0.000000e+00      0      1
2        1.462514e-06  4.258308e-07  0.000000e+00      0      1
3        1.950233e-06  5.653865e-07  0.000000e+00      0      1
4        2.427283e-06  7.074600e-07  4.486659e-08      0      1
...               ...           ...           ...    ...    ...
4237902  2.574302e-05  1.416464e-05  2.218771e-05      0     36
4237903  2.573004e-05  1.418005e-05  2.218419e-05      0     36
4237904  2.571932e-05  1.419285e-05  2.218109e-05      0     36
4237905  2.571058e-05  1.420334e-05  2.217842e-05      0     36
4237906  2.570355e-05  1.421181e-05  2.217615e-05      0     36

[4237907 rows x 11 columns]
          time  channel1  channel2  channel3  channel4  channel5  channel6  \
0            1  0.505663  0.426684  0.000000  0.569724  0.000000  0.098621
1            5  0.540232  0.521757  0.077848  0.747488  0.000000  0.207517
2            6  0.574307  0.618733  0.302852  0.923943  0.000000  0.314503
3            7  0.607811  0.717485  0.526282  1.098786  0.000000  0.419383
4            8  0.640667  0.817878  0.747786  1.271718  0.000000  0.521969
...        ...       ...       ...       ...       ...       ...       ...
4237902  50962  1.788038  1.957604  4.085815  1.574949  5.676281  4.573566
4237903  50963  1.784848  1.957495  4.082814  1.576233  5.682195  4.571260
4237904  50964  1.782188  1.957413  4.080302  1.577300  5.687095  4.569356
4237905  50965  1.780000  1.957352  4.078227  1.578175  5.691099  4.567802
4237906  50966  1.778226  1.957306  4.076537  1.578882  5.694322  4.566553

             channel7      channel8  class  label
0        1.549889e-07  0.000000e+00      0      1
1        2.889740e-07  0.000000e+00      0      1
2        4.258308e-07  0.000000e+00      0      1
3        5.653865e-07  0.000000e+00      0      1
4        7.074600e-07  4.486659e-08      0      1
...               ...           ...    ...    ...
4237902  1.416464e-05  2.218771e-05      0     36
4237903  1.418005e-05  2.218419e-05      0     36
4237904  1.419285e-05  2.218109e-05      0     36
4237905  1.420334e-05  2.217842e-05      0     36
4237906  1.421181e-05  2.217615e-05      0     36

[4237907 rows x 11 columns]
          time  channel1  channel2  channel3  channel4  channel5  channel6  \
0            1  0.505663  0.426684  0.000000  0.569724  0.000000  0.098621
1            5  0.540232  0.521757  0.077848  0.747488  0.000000  0.207517
2            6  0.574307  0.618733  0.302852  0.923943  0.000000  0.314503
3            7  0.607811  0.717485  0.526282  1.098786  0.000000  0.419383
4            8  0.640667  0.817878  0.747786  1.271718  0.000000  0.521969
...        ...       ...       ...       ...       ...       ...       ...
4237902  50962  1.788038  1.957604  4.085815  1.574949  5.676281  4.573566
4237903  50963  1.784848  1.957495  4.082814  1.576233  5.682195  4.571260
4237904  50964  1.782188  1.957413  4.080302  1.577300  5.687095  4.569356
4237905  50965  1.780000  1.957352  4.078227  1.578175  5.691099  4.567802
4237906  50966  1.778226  1.957306  4.076537  1.578882  5.694322  4.566553

         channel7      channel8  class  label
0        0.035534  0.000000e+00      0      1
1        0.066253  0.000000e+00      0      1
2        0.097629  0.000000e+00      0      1
3        0.129625  0.000000e+00      0      1
4        0.162198  4.486659e-08      0      1
...           ...           ...    ...    ...
4237902  3.862965  2.218771e-05      0     36
4237903  3.867166  2.218419e-05      0     36
4237904  3.870658  2.218109e-05      0     36
4237905  3.873519  2.217842e-05      0     36
4237906  3.875829  2.217615e-05      0     36

[4237907 rows x 11 columns]
          time  channel1  channel2  channel3  channel4  channel5  channel6  \
0            1  0.505663  0.426684  0.000000  0.569724  0.000000  0.098621
1            5  0.540232  0.521757  0.077848  0.747488  0.000000  0.207517
2            6  0.574307  0.618733  0.302852  0.923943  0.000000  0.314503
3            7  0.607811  0.717485  0.526282  1.098786  0.000000  0.419383
4            8  0.640667  0.817878  0.747786  1.271718  0.000000  0.521969
...        ...       ...       ...       ...       ...       ...       ...
4237902  50962  1.788038  1.957604  4.085815  1.574949  5.676281  4.573566
4237903  50963  1.784848  1.957495  4.082814  1.576233  5.682195  4.571260
4237904  50964  1.782188  1.957413  4.080302  1.577300  5.687095  4.569356
4237905  50965  1.780000  1.957352  4.078227  1.578175  5.691099  4.567802
4237906  50966  1.778226  1.957306  4.076537  1.578882  5.694322  4.566553

         channel7  channel8  class  label
0        0.035534  0.000000      0      1
1        0.066253  0.000000      0      1
2        0.097629  0.000000      0      1
3        0.129625  0.000000      0      1
4        0.162198  0.008943      0      1
...           ...       ...    ...    ...
4237902  3.862965  4.831329      0     36
4237903  3.867166  4.830561      0     36
4237904  3.870658  4.829887      0     36
4237905  3.873519  4.829305      0     36
4237906  3.875829  4.828811      0     36

[4237907 rows x 11 columns]
Finishing Preprocessing dataset

,time,channel1,channel2,channel3,channel4,channel5,channel6,channel7,channel8,class,label
0,1,0.505663,0.426684,0.000000,0.569724,0.000000,0.098621,0.035534,0.000000,0,1
1,5,0.540232,0.521757,0.077848,0.747488,0.000000,0.207517,0.066253,0.000000,0,1
2,6,0.574307,0.618733,0.302852,0.923943,0.000000,0.314503,0.097629,0.000000,0,1
3,7,0.607811,0.717485,0.526282,1.098786,0.000000,0.419383,0.129625,0.000000,0,1
4,8,0.640667,0.817878,0.747786,1.271718,0.000000,0.521969,0.162198,0.008943,0,1
...,...,...,...,...,...,...,...,...,...,...,...
4237902,50962,1.788038,1.957604,4.085815,1.574949,5.676281,4.573566,3.862965,4.831329,0,36
4237903,50963,1.784848,1.957495,4.082814,1.576233,5.682195,4.571260,3.867166,4.830561,0,36
4237904,50964,1.782188,1.957413,4.080302,1.577300,5.687095,4.569356,3.870658,4.829887,0,36
4237905,50965,1.780000,1.957352,4.078227,1.578175,5.691099,4.567802,3.873519,4.829305,0,36
4237906,50966,1.778226,1.957306,4.076537,1.578882,5.694322,4.566553,3.875829,4.828811,0,36

In [4]:
def create_sliding_windows(data, window_size, step_size, channels):
    X, y = [], []
    for (subj, cls_val), group in data.groupby(['label', 'class']):
        group_vals = group[channels].values

        for i in range(0, len(group_vals) - window_size + 1, step_size):
            window = group_vals[i : i + window_size]
            X.append(window)
            y.append(cls_val)
            
    return np.array(X), np.array(y)

In [ ]:
def prepare_emg_data_for_cnn(csv_file, window_size=200, step_size=50):
    df = pd.read_csv(csv_file)
    df = df[df['class'] != 0]
    df['class'] = df['class'] - 1

    train_subjects = list(range(1, 31))
    test_subjects = list(range(31, 37))

    train_df = df[df['label'].isin(train_subjects)]
    test_df = df[df['label'].isin(test_subjects)]

    channels = [f'channel{i}' for i in range(1, 9)]

    print("Slicing Training set")
    X_train, y_train = create_sliding_windows(train_df, window_size, step_size, channels)

    print("Slicing Testing set")
    X_test, y_test = create_sliding_windows(test_df, window_size, step_size, channels)

    print(f"X_train shape: {X_train.shape}")
    print(f"y_train shape: {y_train.shape}")
    print(f"X_test shape:  {X_test.shape}")
    print(f"y_test shape:  {y_test.shape}")

    return X_train, y_train, X_test, y_test

X_train, y_train, X_test, y_test = prepare_emg_data_for_cnn('datasets/train/EMG-data_processed.csv', window_size=200, step_size=50)

Slicing Training set
Slicing Testing set
X_train shape: (24726, 200, 8)
y_train shape: (24726,)
X_test shape:  (4769, 200, 8)
y_test shape:  (4769,)

In [19]:
def build_and_train_cnn(X_train, y_train, X_test, y_test, num_classes=7):
    input_shape = (X_train.shape[1], X_train.shape[2])
    model = Sequential([
        Conv1D(filters=32, kernel_size=3, kernel_regularizer=tf.keras.regularizers.l2(1e-4), activation='relu', input_shape=input_shape),
        BatchNormalization(),
        MaxPooling1D(pool_size=2),

        Conv1D(filters=64, kernel_size=3, kernel_regularizer=tf.keras.regularizers.l2(1e-4), activation='relu'),
        BatchNormalization(),
        MaxPooling1D(pool_size=2),

        Flatten(),
        Dense(128, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(1e-4)),
        Dropout(0.3),
        Dense(num_classes, activation='softmax')
    ])

    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), 
                  loss='sparse_categorical_crossentropy', 
                  metrics=['accuracy'])

    callbacks = [
        ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=4, min_lr=1e-5, verbose=1),
        EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
    ]

    print("============== Model Summary: ==============")
    model.summary()

    print("Starting Training......")

    history = model.fit(X_train, y_train, 
                        epochs=50,       
                        batch_size=64,      
                        validation_data=(X_test, y_test),
                        callbacks=callbacks)
    
    test_loss, test_acc = model.evaluate(X_test, y_test)
    print(f"Test accuracy: {test_acc * 100:.2f}%")
    
    return model, history

model, history = build_and_train_cnn(X_train, y_train, X_test, y_test, num_classes=7)

============== Model Summary: ==============

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_8 (Conv1D)               │ (None, 198, 32)        │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_8           │ (None, 198, 32)        │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_8 (MaxPooling1D)  │ (None, 99, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_9 (Conv1D)               │ (None, 97, 64)         │         6,208 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_9           │ (None, 97, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_9 (MaxPooling1D)  │ (None, 48, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_4 (Flatten)             │ (None, 3072)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 128)            │       393,344 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 7)              │           903 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 401,159 (1.53 MB)

 Trainable params: 400,967 (1.53 MB)

 Non-trainable params: 192 (768.00 B)

Starting Training......
Epoch 1/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.5974 - loss: 1.4313 - val_accuracy: 0.4928 - val_loss: 4.1906 - learning_rate: 0.0010
Epoch 2/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.7470 - loss: 0.8045 - val_accuracy: 0.5990 - val_loss: 1.1726 - learning_rate: 0.0010
Epoch 3/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.7830 - loss: 0.6359 - val_accuracy: 0.7331 - val_loss: 0.6957 - learning_rate: 0.0010
Epoch 4/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8275 - loss: 0.4949 - val_accuracy: 0.7681 - val_loss: 0.6972 - learning_rate: 0.0010
Epoch 5/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8136 - loss: 0.5017 - val_accuracy: 0.7766 - val_loss: 0.5947 - learning_rate: 0.0010
Epoch 6/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8402 - loss: 0.4650 - val_accuracy: 0.7428 - val_loss: 0.6436 - learning_rate: 0.0010
Epoch 7/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.8501 - loss: 0.3851 - val_accuracy: 0.7838 - val_loss: 0.5098 - learning_rate: 0.0010
Epoch 8/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8407 - loss: 0.4040 - val_accuracy: 0.7536 - val_loss: 0.7723 - learning_rate: 0.0010
Epoch 9/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8519 - loss: 0.4089 - val_accuracy: 0.7150 - val_loss: 0.7113 - learning_rate: 0.0010
Epoch 10/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8623 - loss: 0.3591 - val_accuracy: 0.7862 - val_loss: 0.6363 - learning_rate: 0.0010
Epoch 11/50
52/53 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8693 - loss: 0.3568
Epoch 11: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8692 - loss: 0.3568 - val_accuracy: 0.7621 - val_loss: 0.6863 - learning_rate: 0.0010
Epoch 12/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8778 - loss: 0.3071 - val_accuracy: 0.7971 - val_loss: 0.5850 - learning_rate: 5.0000e-04
Epoch 13/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8992 - loss: 0.2739 - val_accuracy: 0.7524 - val_loss: 0.7155 - learning_rate: 5.0000e-04
Epoch 14/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.8884 - loss: 0.2917 - val_accuracy: 0.7886 - val_loss: 0.6020 - learning_rate: 5.0000e-04
Epoch 15/50
50/53 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9186 - loss: 0.2475
Epoch 15: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.9181 - loss: 0.2482 - val_accuracy: 0.7959 - val_loss: 0.5722 - learning_rate: 5.0000e-04
Epoch 16/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.9100 - loss: 0.2395 - val_accuracy: 0.7911 - val_loss: 0.5787 - learning_rate: 2.5000e-04
Epoch 17/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.9283 - loss: 0.2139 - val_accuracy: 0.7826 - val_loss: 0.5902 - learning_rate: 2.5000e-04
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7873 - loss: 0.5116
Test accuracy: 78.38%

### 3 Channel Dataset

In [7]:
import os
import glob

def preprocess_emg_signal(df, fs=1000):
    df_processed = df.copy()
    channels = [f'Channel {i}' for i in range(1, 4)]
    nyq = 0.5 * fs
    b_band, a_band = butter(4, [20/nyq, 450/nyq], btype='band')
    b_low, a_low = butter(4, 10/nyq, btype='low')

    for ch in channels:
        if ch not in df.columns:
            print(f"Warning: cannot find Channel {ch} in the file!")
            continue
        raw_sig = df[ch].fillna(0).values
        filtered = filtfilt(b_band, a_band, raw_sig)
        rectified = np.abs(filtered)
        envelope = filtfilt(b_low, a_low, rectified)
        envelope = np.maximum(envelope, 0)
        df_processed[ch] = envelope 
        
        max_val = np.max(envelope)
        if max_val == 0: max_val = 1
        
        df_processed[ch] = (envelope / max_val) * 100
        print(df_processed)

    return df_processed

def load_and_preprocess_dataset(path_input, fs=1000):
    all_processed_dfs = []
    if isinstance(path_input, list):
        csv_files = path_input
    elif os.path.isfile(path_input):
        csv_files = [path_input]
    elif os.path.isdir(path_input):
        csv_files = glob.glob(os.path.join(path_input, "**", "*.csv"), recursive=True)
    else:
        csv_files = glob.glob(path_input)
    if not csv_files:
        print("Cannot read file path")
        return None
    
    for file_path in csv_files:
        if not os.path.exists(file_path):
            print(f"File {file_path} not exist")
            continue
        df = pd.read_csv(file_path)
        df_clean = preprocess_emg_signal(df)
        if 'G1' in file_path or 'Resting' in file_path:
            df_clean['class'] = 0
        elif 'G2' in file_path or 'Fist' in file_path:
            df_clean['class'] = 1
        elif 'G4' in file_path or 'Open_Hand' in file_path:
            df_clean['class'] = 2
        elif 'G7' in file_path or 'Pointing' in file_path:
            df_clean['class'] = 3
        
        all_processed_dfs.append(df_clean)
        print(f"Finishing Preprocessing of {file_path}")
    if not all_processed_dfs:
        print("No dataset")
        return None
    
    full_dataset = pd.concat(all_processed_dfs, ignore_index=False)
    
    
    return full_dataset

In [8]:
all_file_paths = []
for i in range(1, 16):
    all_file_paths.append(f"datasets/train/1st_Gesture_Resting/P1_G1_Resting_R{i:02d} .csv")
    all_file_paths.append(f"datasets/train/2nd_Gesture_Fist/P1_G2_Fist_R{i:02d} .csv")
    all_file_paths.append(f"datasets/train/4th_Gesture_Open_Hand/P1_G4_Open_Hand_R{i:02d} .csv")
    all_file_paths.append(f"datasets/train/7th_Gesture_Pointing/P1_G7_Pointing_R{i:02d} .csv")

full_data = load_and_preprocess_dataset(all_file_paths)
full_data

      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   0.000000  -0.004272  -0.002792
1             2   0.000000  -0.001311   0.000993
2             3   0.000000  -0.000817  -0.000324
3             4   0.000000  -0.001804  -0.001804
4             5   2.281087  -0.003285   0.000335
...         ...        ...        ...        ...
3495       3496  78.102589  -0.002792  -0.003614
3496       3497  78.092183  -0.001146  -0.000488
3497       3498  78.083147  -0.000488  -0.003779
3498       3499  78.075400  -0.000324  -0.002956
3499       3500  78.068852  -0.002463  -0.001640

[3500 rows x 4 columns]

      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   0.000000   3.069438  -0.002792
1             2   0.000000   6.057246   0.000993
2             3   0.000000   9.040095  -0.000324
3             4   0.000000  12.012870  -0.001804
4             5   2.281087  14.970484   0.000335
...         ...        ...        ...        ...
3495       3496  78.102589  56.573898  -0.003614
3496       3497  78.092183  56.553343  -0.000488
3497       3498  78.083147  56.536086  -0.003779
3498       3499  78.075400  56.521776  -0.002956
3499       3500  78.068852  56.510076  -0.001640

[3500 rows x 4 columns]
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   0.000000   3.069438  20.153196
1             2   0.000000   6.057246  21.756759
2             3   0.000000   9.040095  23.387035
3             4   0.000000  12.012870  25.041898
4             5   2.281087  14.970484  26.719168
...         ...        ...        ...        ...
3495       3496  78.102589  56.573898  51.470395
3496       3497  78.092183  56.553343  51.460919
3497       3498  78.083147  56.536086  51.452850
3498       3499  78.075400  56.521776  51.446061
3499       3500  78.068852  56.510076  51.440428

[3500 rows x 4 columns]
Finishing Preprocessing of datasets/train/1st_Gesture_Resting/P1_G1_Resting_R01 .csv
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   0.770963  -0.002133  -0.000159
1             2   0.843900  -0.000653  -0.004108
2             3   0.917678  -0.001804  -0.003285
3             4   0.992135  -0.002627  -0.001969
4             5   1.067111  -0.003121  -0.002463
...         ...        ...        ...        ...
3495       3496  26.063257  -0.000324  -0.001804
3496       3497  26.046037  -0.002463   0.000664
3497       3498  26.031559  -0.004766  -0.000982
3498       3499  26.019544  -0.006905   0.001980
3499       3500  26.009721  -0.004602   0.000828

[3500 rows x 4 columns]
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   0.770963   0.000000  -0.000159
1             2   0.843900   0.000000  -0.004108
2             3   0.917678   0.197631  -0.003285
3             4   0.992135   0.707878  -0.001969
4             5   1.067111   1.211963  -0.002463
...         ...        ...        ...        ...
3495       3496  26.063257  15.026679  -0.001804
3496       3497  26.046037  15.025397   0.000664
3497       3498  26.031559  15.024301  -0.000982
3498       3499  26.019544  15.023371   0.001980
3499       3500  26.009721  15.022590   0.000828

[3500 rows x 4 columns]
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   0.770963   0.000000   0.000000
1             2   0.843900   0.000000   0.137378
2             3   0.917678   0.197631   1.034514
3             4   0.992135   0.707878   1.925974
4             5   1.067111   1.211963   2.810363
...         ...        ...        ...        ...
3495       3496  26.063257  15.026679  26.890805
3496       3497  26.046037  15.025397  26.894732
3497       3498  26.031559  15.024301  26.897843
3498       3499  26.019544  15.023371  26.900262
3499       3500  26.009721  15.022590  26.902104

[3500 rows x 4 columns]
Finishing Preprocessing of datasets/train/2nd_Gesture_Fist/P1_G2_Fist_R01 .csv
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   3.978770  -0.008057  -0.010689
1             2   4.759298  -0.013651  -0.011677
2             3   5.545031  -0.018916  -0.017765
3             4   6.334492  -0.021055  -0.021220
4             5   7.126178  -0.003614  -0.021714
...         ...        ...        ...        ...
3495       3496  19.838417   0.004448   0.011359
3496       3497  19.827280  -0.001969   0.006752
3497       3498  19.818035  -0.006247  -0.002298
3498       3499  19.810453  -0.005260  -0.013487
3499       3500  19.804321  -0.006082  -0.022701

[3500 rows x 4 columns]
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   3.978770  14.419110  -0.010689
1             2   4.759298  16.414635  -0.011677
2             3   5.545031  18.404291  -0.017765
3             4   6.334492  20.383556  -0.021220
4             5   7.126178  22.347926  -0.021714
...         ...        ...        ...        ...
3495       3496  19.838417  34.962819   0.011359
3496       3497  19.827280  34.930175   0.006752
3497       3498  19.818035  34.903139  -0.002298
3498       3499  19.810453  34.881035  -0.013487
3499       3500  19.804321  34.863223  -0.022701

[3500 rows x 4 columns]
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   3.978770  14.419110   8.956845
1             2   4.759298  16.414635   9.606895
2             3   5.545031  18.404291  10.257830
3             4   6.334492  20.383556  10.908493
4             5   7.126178  22.347926  11.557732
...         ...        ...        ...        ...
3495       3496  19.838417  34.962819  37.196653
3496       3497  19.827280  34.930175  37.187547
3497       3498  19.818035  34.903139  37.179926
3498       3499  19.810453  34.881035  37.173621
3499       3500  19.804321  34.863223  37.168477

[3500 rows x 4 columns]
Finishing Preprocessing of datasets/train/4th_Gesture_Open_Hand/P1_G4_Open_Hand_R01 .csv
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   0.154379  -0.001311  -0.001475
1             2   0.208259  -0.000159   0.000335
2             3   0.262156  -0.003285  -0.002133
3             4   0.315977  -0.001804  -0.004437
4             5   0.369628  -0.005260  -0.005424
...         ...        ...        ...        ...
3495       3496   4.796901   0.003132  -0.010360
3496       3497   4.799774  -0.000488  -0.014145
3497       3498   4.802145   0.001980  -0.009044
3498       3499   4.804076   0.001815  -0.006741
3499       3500   4.805624  -0.000817  -0.002627

[3500 rows x 4 columns]
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   0.154379   0.263325  -0.001475
1             2   0.208259   0.346732   0.000335
2             3   0.262156   0.430616  -0.002133
3             4   0.315977   0.514858  -0.004437
4             5   0.369628   0.599340  -0.005424
...         ...        ...        ...        ...
3495       3496   4.796901   6.131077  -0.010360
3496       3497   4.799774   6.132553  -0.014145
3497       3498   4.802145   6.133752  -0.009044
3498       3499   4.804076   6.134711  -0.006741
3499       3500   4.805624   6.135465  -0.002627

[3500 rows x 4 columns]
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   0.154379   0.263325   1.347287
1             2   0.208259   0.346732   1.578656
2             3   0.262156   0.430616   1.813673
3             4   0.315977   0.514858   2.051902
4             5   0.369628   0.599340   2.292896
...         ...        ...        ...        ...
3495       3496   4.796901   6.131077  17.475030
3496       3497   4.799774   6.132553  17.483919
3497       3498   4.802145   6.133752  17.491240
3498       3499   4.804076   6.134711  17.497184
3499       3500   4.805624   6.135465  17.501934

[3500 rows x 4 columns]
Finishing Preprocessing of datasets/train/7th_Gesture_Pointing/P1_G7_Pointing_R01 .csv
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   9.376003  -0.004766  -0.004108
1             2  11.487639  -0.003779  -0.002133
2             3  13.613195  -0.001311  -0.000982
3             4  15.748205  -0.000982  -0.002298
4             5  17.888185  -0.000982  -0.003943
...         ...        ...        ...        ...
3495       3496  73.250471  -0.001475  -0.004766
3496       3497  73.262204  -0.004108  -0.001969
3497       3498  73.271688  -0.003779  -0.002298
3498       3499  73.279232  -0.003779  -0.003779
3499       3500  73.285125  -0.002956  -0.001146

[3500 rows x 4 columns]
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   9.376003  12.014083  -0.004108
1             2  11.487639  14.970747  -0.002133
2             3  13.613195  17.938007  -0.000982
3             4  15.748205  20.910651  -0.002298
4             5  17.888185  23.883457  -0.003943
...         ...        ...        ...        ...
3495       3496  73.250471  83.250122  -0.004766
3496       3497  73.262204  83.232815  -0.001969
3497       3498  73.271688  83.217967  -0.002298
3498       3499  73.279232  83.205398  -0.003779
3499       3500  73.285125  83.194918  -0.001146

[3500 rows x 4 columns]
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   9.376003  12.014083  17.130608
1             2  11.487639  14.970747  19.069609
2             3  13.613195  17.938007  21.016803
3             4  15.748205  20.910651  22.968467
4             5  17.888185  23.883457  24.920851
...         ...        ...        ...        ...
3495       3496  73.250471  83.250122  60.570287
3496       3497  73.262204  83.232815  60.549173
3497       3498  73.271688  83.217967  60.531416
3498       3499  73.279232  83.205398  60.516671
3499       3500  73.285125  83.194918  60.504603

[3500 rows x 4 columns]
Finishing Preprocessing of datasets/train/1st_Gesture_Resting/P1_G1_Resting_R02 .csv
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   0.482118  -0.004602  -0.003779
1             2   0.597819  -0.003121  -0.006082
2             3   0.713937  -0.001969  -0.002298
3             4   0.830228  -0.000653  -0.000159
4             5   0.946446  -0.000159  -0.001804
...         ...        ...        ...        ...
3495       3496  33.053509  -0.005424  -0.007563
3496       3497  33.047836  -0.007399  -0.007234
3497       3498  33.042859  -0.007070  -0.005095
3498       3499  33.038561  -0.007070  -0.000324
3499       3500  33.034908  -0.007892  -0.001146

[3500 rows x 4 columns]
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   0.482118   0.922094  -0.003779
1             2   0.597819   1.461993  -0.006082
2             3   0.713937   1.999593  -0.002298
3             4   0.830228   2.534011  -0.000159
4             5   0.946446   3.064378  -0.001804
...         ...        ...        ...        ...
3495       3496  33.053509  19.747357  -0.007563
3496       3497  33.047836  19.739076  -0.007234
3497       3498  33.042859  19.732186  -0.005095
3498       3499  33.038561  19.726524  -0.000324
3499       3500  33.034908  19.721936  -0.001146

[3500 rows x 4 columns]
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   0.482118   0.922094   2.726609
1             2   0.597819   1.461993   3.794520
2             3   0.713937   1.999593   4.871849
3             4   0.830228   2.534011   5.957172
4             5   0.946446   3.064378   7.049042
...         ...        ...        ...        ...
3495       3496  33.053509  19.747357  35.175472
3496       3497  33.047836  19.739076  35.175387
3497       3498  33.042859  19.732186  35.175295
3498       3499  33.038561  19.726524  35.175189
3499       3500  33.034908  19.721936  35.175068

[3500 rows x 4 columns]
Finishing Preprocessing of datasets/train/2nd_Gesture_Fist/P1_G2_Fist_R02 .csv
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   2.901376  -0.002463  -0.001311
1             2   3.280089  -0.002463  -0.001969
2             3   3.659040  -0.002463  -0.003285
3             4   4.037503  -0.001311  -0.002298
4             5   4.414754  -0.002627   0.000335
...         ...        ...        ...        ...
3495       3496  18.448695  -0.012499   0.017282
3496       3497  18.449512  -0.011841   0.004284
3497       3498  18.450041   0.006258  -0.006905
3498       3499  18.450349   0.000006  -0.006741
3499       3500  18.450493  -0.003121  -0.005260

[3500 rows x 4 columns]
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   2.901376   1.474544  -0.001311
1             2   3.280089   1.816467  -0.001969
2             3   3.659040   2.154554  -0.003285
3             4   4.037503   2.488066  -0.002298
4             5   4.414754   2.816271   0.000335
...         ...        ...        ...        ...
3495       3496  18.448695  39.018949   0.017282
3496       3497  18.449512  39.004198   0.004284
3497       3498  18.450041  38.991502  -0.006905
3498       3499  18.450349  38.980731  -0.006741
3499       3500  18.450493  38.971739  -0.005260

[3500 rows x 4 columns]
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   2.901376   1.474544   0.793901
1             2   3.280089   1.816467   0.816874
2             3   3.659040   2.154554   0.837987
3             4   4.037503   2.488066   0.857107
4             5   4.414754   2.816271   0.874109
...         ...        ...        ...        ...
3495       3496  18.448695  39.018949  17.449128
3496       3497  18.449512  39.004198  17.451196
3497       3498  18.450041  38.991502  17.452843
3498       3499  18.450349  38.980731  17.454131
3499       3500  18.450493  38.971739  17.455118

[3500 rows x 4 columns]
Finishing Preprocessing of datasets/train/4th_Gesture_Open_Hand/P1_G4_Open_Hand_R02 .csv
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   0.355835  -0.001475  -0.004766
1             2   0.418169  -0.002627  -0.001969
2             3   0.480594  -0.003450  -0.002133
3             4   0.542990  -0.004931  -0.003285
4             5   0.605238  -0.003285  -0.001969
...         ...        ...        ...        ...
3495       3496   6.460364  -0.003614   0.002474
3496       3497   6.458817  -0.003779   0.000499
3497       3498   6.457480  -0.005260  -0.000159
3498       3499   6.456341  -0.001475  -0.004602
3499       3500   6.455385   0.003132  -0.006082

[3500 rows x 4 columns]
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   0.355835   0.651794  -0.004766
1             2   0.418169   0.854695  -0.001969
2             3   0.480594   1.058648  -0.002133
3             4   0.542990   1.263302  -0.003285
4             5   0.605238   1.468305  -0.001969
...         ...        ...        ...        ...
3495       3496   6.460364  33.705697   0.002474
3496       3497   6.458817  33.702221   0.000499
3497       3498   6.457480  33.699036  -0.000159
3498       3499   6.456341  33.696181  -0.004602
3499       3500   6.455385  33.693678  -0.006082

[3500 rows x 4 columns]
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   0.355835   0.651794   0.441119
1             2   0.418169   0.854695   1.099661
2             3   0.480594   1.058648   1.754170
3             4   0.542990   1.263302   2.403630
4             5   0.605238   1.468305   3.047037
...         ...        ...        ...        ...
3495       3496   6.460364  33.705697  50.934497
3496       3497   6.458817  33.702221  50.925897
3497       3498   6.457480  33.699036  50.918170
3498       3499   6.456341  33.696181  50.911359
3499       3500   6.455385  33.693678  50.905478

[3500 rows x 4 columns]
Finishing Preprocessing of datasets/train/7th_Gesture_Pointing/P1_G7_Pointing_R02 .csv
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1  13.827088  -0.000982  -0.003285
1             2  15.102718   0.000006  -0.001475
2             3  16.411585  -0.001475  -0.002792
3             4  17.751818  -0.002956  -0.003779
4             5  19.121479  -0.004766  -0.003614
...         ...        ...        ...        ...
3495       3496  62.310557  -0.002627  -0.002298
3496       3497  62.298391  -0.003943  -0.001804
3497       3498  62.288064  -0.004766  -0.003450
3498       3499  62.279403  -0.003121  -0.002627
3499       3500  62.272238  -0.001475  -0.001475

[3500 rows x 4 columns]
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1  13.827088   9.376481  -0.003285
1             2  15.102718  13.011372  -0.001475
2             3  16.411585  16.626845  -0.002792
3             4  17.751818  20.216882  -0.003779
4             5  19.121479  23.775548  -0.003614
...         ...        ...        ...        ...
3495       3496  62.310557  81.304040  -0.002298
3496       3497  62.298391  81.308559  -0.001804
3497       3498  62.288064  81.311986  -0.003450
3498       3499  62.279403  81.314504  -0.002627
3499       3500  62.272238  81.316286  -0.001475

[3500 rows x 4 columns]
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1  13.827088   9.376481  16.876300
1             2  15.102718  13.011372  18.608406
2             3  16.411585  16.626845  20.371465
3             4  17.751818  20.216882  22.162891
4             5  19.121479  23.775548  23.980027
...         ...        ...        ...        ...
3495       3496  62.310557  81.304040  66.754292
3496       3497  62.298391  81.308559  66.733910
3497       3498  62.288064  81.311986  66.716740
3498       3499  62.279403  81.314504  66.702451
3499       3500  62.272238  81.316286  66.690723

[3500 rows x 4 columns]
Finishing Preprocessing of datasets/train/1st_Gesture_Resting/P1_G1_Resting_R03 .csv
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   0.000000  -0.001475  -0.004766
1             2   0.000000  -0.000982  -0.001146
2             3   0.000000  -0.001475   0.000006
3             4   0.043831  -0.002627  -0.004437
4             5   0.217890  -0.004766  -0.005095
...         ...        ...        ...        ...
3495       3496  50.149464  -0.006576  -0.002627
3496       3497  50.124933  -0.004931  -0.003614
3497       3498  50.104042  -0.003285  -0.005918
3498       3499  50.086496  -0.005589  -0.004272
3499       3500  50.071987  -0.005753   0.000006

[3500 rows x 4 columns]
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   0.000000   3.857134  -0.004766
1             2   0.000000   4.255238  -0.001146
2             3   0.000000   4.661672   0.000006
3             4   0.043831   5.075757  -0.004437
4             5   0.217890   5.496786  -0.005095
...         ...        ...        ...        ...
3495       3496  50.149464  26.029716  -0.002627
3496       3497  50.124933  26.011495  -0.003614
3497       3498  50.104042  25.996279  -0.005918
3498       3499  50.086496  25.983735  -0.004272
3499       3500  50.071987  25.973542   0.000006

[3500 rows x 4 columns]
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   0.000000   3.857134   1.427709
1             2   0.000000   4.255238   2.019761
2             3   0.000000   4.661672   2.625644
3             4   0.043831   5.075757   3.244559
4             5   0.217890   5.496786   3.875675
...         ...        ...        ...        ...
3495       3496  50.149464  26.029716  31.261859
3496       3497  50.124933  26.011495  31.262819
3497       3498  50.104042  25.996279  31.263344
3498       3499  50.086496  25.983735  31.263548
3499       3500  50.071987  25.973542  31.263526

[3500 rows x 4 columns]
Finishing Preprocessing of datasets/train/2nd_Gesture_Fist/P1_G2_Fist_R03 .csv
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   0.000000  -0.003285  -0.005260
1             2   0.000000  -0.002298  -0.004108
2             3   0.000000  -0.000817  -0.001475
3             4   0.489756  -0.002133  -0.003779
4             5   1.185972  -0.003614  -0.003450
...         ...        ...        ...        ...
3495       3496  25.166998  -0.004108   0.004777
3496       3497  25.159965   0.005271   0.022712
3497       3498  25.154015  -0.002298   0.012675
3498       3499  25.149044  -0.011512   0.005435
3499       3500  25.144951  -0.001475  -0.006576

[3500 rows x 4 columns]
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   0.000000   2.321186  -0.005260
1             2   0.000000   2.462289  -0.004108
2             3   0.000000   2.606330  -0.001475
3             4   0.489756   2.753024  -0.003779
4             5   1.185972   2.902078  -0.003450
...         ...        ...        ...        ...
3495       3496  25.166998  20.029641   0.004777
3496       3497  25.159965  20.008444   0.022712
3497       3498  25.154015  19.990893   0.012675
3498       3499  25.149044  19.976547   0.005435
3499       3500  25.144951  19.964989  -0.006576

[3500 rows x 4 columns]
      Time (ms)  Channel 1  Channel 2  Channel 3
0             1   0.000000   2.321186   0.335661
1             2   0.000000   2.462289   0.412787

      Time (ms)  Channel 1  Channel 2  Channel 3  class
0             1   0.000000   3.069438  20.153196      0
1             2   0.000000   6.057246  21.756759      0
2             3   0.000000   9.040095  23.387035      0
3             4   0.000000  12.012870  25.041898      0
4             5   2.281087  14.970484  26.719168      0
...         ...        ...        ...        ...    ...
3495       3496  18.321573  43.255349  51.472016      3
3496       3497  18.300691  43.273564  51.446070      3
3497       3498  18.283353  43.288695  51.424178      3
3498       3499  18.269143  43.301089  51.405948      3
3499       3500  18.257666  43.311082  51.390989      3

[210000 rows x 5 columns]

In [14]:
def create_sliding_windows(data, window_size, step_size, channels):
    X, y = [], []
    for cls_val, group in data.groupby(['class']):
        group_vals = group[channels].values
        for i in range(0, len(group_vals) - window_size + 1, step_size):
            window = group_vals[i : i + window_size]
            X.append(window)
            y.append(cls_val)
            
    return np.array(X), np.array(y)

def prepare_emg_data_for_cnn(df, window_size=200, step_size=50):
    df_clean = df.copy()

    channels = [f'Channel {i}' for i in range(1, 4)]

    if 'label' in df_clean.columns:
        train_subjects = list(range(1, 31))
        test_subjects = list(range(31, 37))

        train_df = df_clean[df_clean['label'].isin(train_subjects)]
        test_df = df_clean[df_clean['label'].isin(test_subjects)]
    else:
        split_idx = int(len(df_clean) * 0.8)
        train_df = df_clean.iloc[:split_idx]
        test_df = df_clean.iloc[split_idx:]

    print("Slicing Training set")
    X_train, y_train = create_sliding_windows(train_df, window_size, step_size, channels)

    print("Slicing Testing set")
    X_test, y_test = create_sliding_windows(test_df, window_size, step_size, channels)

    print(f"X_train shape: {X_train.shape}")
    print(f"y_train shape: {y_train.shape}")
    print(f"X_test shape:  {X_test.shape}")
    print(f"y_test shape:  {y_test.shape}")

    return X_train, y_train, X_test, y_test

X_train, y_train, X_test, y_test = prepare_emg_data_for_cnn(full_data)

Slicing Training set
Slicing Testing set
X_train shape: (3348, 200, 3)
y_train shape: (3348, 1)
X_test shape:  (828, 200, 3)
y_test shape:  (828, 1)

In [20]:
model, history = build_and_train_cnn(X_train, y_train, X_test, y_test, num_classes=4)

============== Model Summary: ==============

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_10 (Conv1D)              │ (None, 198, 32)        │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_10          │ (None, 198, 32)        │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_10 (MaxPooling1D) │ (None, 99, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_11 (Conv1D)              │ (None, 97, 64)         │         6,208 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_11          │ (None, 97, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_11 (MaxPooling1D) │ (None, 48, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_5 (Flatten)             │ (None, 3072)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 128)            │       393,344 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 4)              │           516 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 400,772 (1.53 MB)

 Trainable params: 400,580 (1.53 MB)

 Non-trainable params: 192 (768.00 B)

Starting Training......
Epoch 1/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - accuracy: 0.6460 - loss: 1.3101 - val_accuracy: 0.5000 - val_loss: 5.3966 - learning_rate: 0.0010
Epoch 2/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.7607 - loss: 0.7747 - val_accuracy: 0.6220 - val_loss: 1.4480 - learning_rate: 0.0010
Epoch 3/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8099 - loss: 0.6243 - val_accuracy: 0.7005 - val_loss: 1.1537 - learning_rate: 0.0010
Epoch 4/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8099 - loss: 0.5203 - val_accuracy: 0.7633 - val_loss: 0.7920 - learning_rate: 0.0010
Epoch 5/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8094 - loss: 0.5348 - val_accuracy: 0.7500 - val_loss: 0.7376 - learning_rate: 0.0010
Epoch 6/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8179 - loss: 0.5200 - val_accuracy: 0.7500 - val_loss: 0.6767 - learning_rate: 0.0010
Epoch 7/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8485 - loss: 0.4175 - val_accuracy: 0.7729 - val_loss: 0.6525 - learning_rate: 0.0010
Epoch 8/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8546 - loss: 0.3963 - val_accuracy: 0.7826 - val_loss: 0.6691 - learning_rate: 0.0010
Epoch 9/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8443 - loss: 0.3917 - val_accuracy: 0.7572 - val_loss: 0.7377 - learning_rate: 0.0010
Epoch 10/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.8666 - loss: 0.3554 - val_accuracy: 0.8007 - val_loss: 0.5653 - learning_rate: 0.0010
Epoch 11/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8635 - loss: 0.3453 - val_accuracy: 0.7548 - val_loss: 0.7601 - learning_rate: 0.0010
Epoch 12/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8746 - loss: 0.3464 - val_accuracy: 0.8043 - val_loss: 0.5624 - learning_rate: 0.0010
Epoch 13/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8894 - loss: 0.3084 - val_accuracy: 0.7983 - val_loss: 0.6523 - learning_rate: 0.0010
Epoch 14/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8808 - loss: 0.3363 - val_accuracy: 0.7729 - val_loss: 0.6960 - learning_rate: 0.0010
Epoch 15/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8864 - loss: 0.3292 - val_accuracy: 0.7790 - val_loss: 0.6420 - learning_rate: 0.0010
Epoch 16/50
52/53 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8822 - loss: 0.3120
Epoch 16: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8820 - loss: 0.3123 - val_accuracy: 0.8140 - val_loss: 0.6150 - learning_rate: 0.0010
Epoch 17/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8942 - loss: 0.2794 - val_accuracy: 0.7886 - val_loss: 0.5829 - learning_rate: 5.0000e-04
Epoch 18/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.9083 - loss: 0.2550 - val_accuracy: 0.7862 - val_loss: 0.6354 - learning_rate: 5.0000e-04
Epoch 19/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.9119 - loss: 0.2629 - val_accuracy: 0.8068 - val_loss: 0.5860 - learning_rate: 5.0000e-04
Epoch 20/50
52/53 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9235 - loss: 0.2316
Epoch 20: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.9233 - loss: 0.2316 - val_accuracy: 0.7609 - val_loss: 0.7251 - learning_rate: 5.0000e-04
Epoch 21/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.9206 - loss: 0.2320 - val_accuracy: 0.7874 - val_loss: 0.6807 - learning_rate: 2.5000e-04
Epoch 22/50
53/53 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.9302 - loss: 0.2096 - val_accuracy: 0.7935 - val_loss: 0.6528 - learning_rate: 2.5000e-04
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.5175
Test accuracy: 80.43%